### PR TITLE
BBC Micro version

### PR DESCRIPTION
**Pull request by pau1ie**
Thanks for this program. I have made some changes to your version, to help people view files online. Probably best to have a look at the Explore Disc button for games on bbcmicro.co.uk to see how it works. I attempted to:

- Display text files 
- Detokenise BASIC files (Converted swehs MMBUTILS detokeniser into javascript, with permission to change the license)
- HEX dump
- Disassembly
- Display images using your BBC Web Image filer

I also make some attempt to work out what the most appropriate file is. Lastly I made a start at attempting to support dsd images. I didn't find any bugs in your code, but I expect I have introduced bugs. I would be amazed if there weren't bugs in the disassembly routine.

### CODE REVIEW

**Comment by shawty** [comment]
Awesome, I'll check this out during the week :-)

**Comment by shawty** [comment]
All looking good, not actually tested it yet, but code reads ok. :-)

Looks a lot like some of the first code I ever wrote :-)  you get a tsk,tsk from me for the single letter var names ;-)

**Comment by pau1ie** [comment]
Yes, sorry, it could be more readable. Glad you found it useful though.

**Comment by shawty** [comment]
LOL... oh trust me Paulie, I'm just teasing you.... it's paradise to read compared to the state of some of the software I've delt with in my career so far...

There's a reason why senior/lead devs like me are grumpy bastards :-D

**Pull request merged**
